services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: "./.render/build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
